# Generated by Django 5.1.1 on 2025-09-08 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_remote', models.BooleanField(default=False)),
                ('remote_platform', models.CharField(blank=True, max_length=120)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.discipline')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='directory.studentgroup')),
                ('lesson_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.lessontype')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='directory.room')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='directory.teacher')),
            ],
            options={
                'ordering': ['date', 'timeslot__order'],
            },
        ),
        migrations.CreateModel(
            name='HomeworkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='scheduleapp.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('order', 'start_time', 'end_time')},
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='timeslot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scheduleapp.timeslot'),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('date', 'timeslot', 'group')},
        ),
    ]
