# Generated by Django 5.1.1 on 2025-09-08 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(default='RANEPA', max_length=64)),
                ('params', models.JSONField(default=dict)),
                ('totals', models.JSONField(default=dict)),
                ('reasons', models.JSONField(default=dict)),
                ('samples', models.JSONField(default=list)),
                ('log_file', models.CharField(blank=True, default='', max_length=255)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
