# Generated by Django 5.1.1 on 2025-09-08 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleapp', '0002_importjob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importjob',
            options={'ordering': ['-created_at'], 'verbose_name': 'Импорт', 'verbose_name_plural': 'Импорты'},
        ),
        migrations.AlterField(
            model_name='importjob',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='log_file',
            field=models.CharField(blank=True, max_length=255, verbose_name='Файл лога'),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='params',
            field=models.JSONField(blank=True, default=dict, verbose_name='Параметры запроса'),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='reasons',
            field=models.JSONField(blank=True, default=dict, verbose_name='Причины'),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='samples',
            field=models.JSONField(blank=True, default=list, verbose_name='Примеры проблемных записей'),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='source',
            field=models.CharField(choices=[('RANEPA', 'RANEPA'), ('OTHER', 'Other')], default='RANEPA', max_length=32, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='totals',
            field=models.JSONField(blank=True, default=dict, verbose_name='Итоги'),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
