# Generated by Django 5.1.1 on 2025-09-12 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleapp', '0003_alter_importjob_options_alter_importjob_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_stream',
            field=models.BooleanField(default=False, help_text='Потоковая лекция (одно занятие для нескольких групп одновременно)'),
        ),
    ]
