# Generated by Django 5.1.1 on 2025-09-08 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_holiday_teachingassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='default_lesson_type',
            field=models.ForeignKey(blank=True, help_text='Тип занятия по умолчанию (лекция/практика/лабораторная и т.д.)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.lessontype'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='delivery_mode',
            field=models.CharField(choices=[('in_person', 'Очная'), ('remote', 'Дистанционная'), ('mixed', 'Смешанная')], default='in_person', max_length=16),
        ),
        migrations.AddField(
            model_name='discipline',
            name='required_room_type',
            field=models.ForeignKey(blank=True, help_text='Если задан, дисциплина должна проводиться в аудитории этого типа', null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.roomtype'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='requires_computers',
            field=models.BooleanField(default=False, help_text='Требуются компьютеры по числу студентов (для компьютерных дисциплин)'),
        ),
        migrations.CreateModel(
            name='BuildingPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.building')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_prefs', to='directory.discipline')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_prefs', to='directory.studentgroup')),
            ],
            options={
                'ordering': ['priority', 'building__name'],
                'unique_together': {('group', 'discipline', 'building')},
            },
        ),
    ]
